### ISSUE TITLE
Nice to have - Manifest classpath entries at the bottom

### ISSUE THREAD

**Issue by Vity01** [coditory/gradle-manifest-plugin#10]
We have a project with many dependencies (> 40) and the `Class-Path: ` attribute value can be quite long (more than 2 pages...). I think it would be nice to put other attributes up - before the `Class-Path: ` in the manifest file. 
IMHO the fix is quite easy, just to move `.plus(classpathAttribute(project, extension))` (in `ManifestAttributes.kt`) as the last part added - according to kotlindoc, the `plus()` returns  `LinkedHashMap` so the order is preserved (and the Attributes interface implementation also uses `LinkedHashMap`)

**Comment by pmendelski** [comment]
Hi, I moved `Class-Path` attribute lower in version `0.1.13`.

**Comment by Vity01** [comment]
Great, thank you!
