### ISSUE TITLE
How Do I Skip The SCM Attributes?

### ISSUE THREAD

**Issue by opticyclic** [coditory/gradle-manifest-plugin#2]
I don't want to include the SCM* attributes in my manifest.

Is there any way to prevent them being generated?

**Comment by pmendelski** [comment]
Hi, sorry it took so long.

You can use:
```
manifest {
    scmAttributes = false
}
```

Details are in the [readme](https://github.com/coditory/gradle-manifest-plugin#overriding-generated-attributes).
