### ISSUE TITLE
Invalid manifest generated when build host name contains newlines

### ISSUE THREAD

**Issue by Dogacel** [coditory/gradle-manifest-plugin#24]
For some reason, my hostname contains a new line on the end.

```
> hostname
...-MacBook-Pro-dogac.local

```

And this causes `java.io.IOException: invalid manifest format` when importing the jars from another project.

Can we just trim the newline at the end of the hostname?

```
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

**Comment by pmendelski** [comment]
Hi, check version `0.2.2`

**Comment by Dogacel** [comment]
@pmendelski that was so quick, thank you so much 🙇
