### ISSUE TITLE
Feature Request: Support for Class-Path attribute

### ISSUE THREAD

**Issue by Vity01** [coditory/gradle-manifest-plugin#3]
Hello,
your plugin looks very usable and I really like it, but I miss one feature - to add current dependencies to the class-path attribute if it's required. 
https://docs.oracle.com/javase/tutorial/deployment/jar/downman.html
It's usually implemented by adding 
```
"Class-Path":  configurations.implementation.collect { someFolderPrefix + it.name }.join(' ')
```
it would be nice not to be necessary to spread this code across my multiple projects.

**Comment by pmendelski** [comment]
Hi, thanks for submitting feature request.

This feature requires adding configuration parameter to specify `someFolderPrefix` from you snippet. Eventually you would replace one snippet of code with another:

```
manifest {
    addClasspathWithPrefix("myLibFolder")
}
```

Is it any better?

**Comment by pmendelski** [comment]
Branch is [ready](https://github.com/coditory/gradle-manifest-plugin/tree/add-attribute-filters-and-classpath-generator#generating-classpath-attribute). Please let me know if it solves your problem.

**Comment by Vity01** [comment]
@pmendelski thank you very much for the quick update. I really appreciate it. 
I have one suggestion for the code: 
```
configurations.getByName("runtime).files
```
replace with
```
configurations.getByName(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME).files
```
It looks like "runtime" is marked as deprecated.

The only thing I am unsure is if this solution will work for some more complex project structure - we will see - I will report it if I find such project.

**Comment by pmendelski** [comment]
@Vity01 I applied your suggestion. Thanks for code review.
I checked the plugin on few projects of mine. Did not found any issues.
Let me know If you find any.

Change is released in v0.1.11.

**Comment by Vity01** [comment]
Excellent, thank you very much and keep up the good work!

**Comment by Vity01** [comment]
FYI - I just found a difference between the 'runtime` and `runtimeClasspath` and why using `JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME` is important.
If you use `implementation lib` with the `runtime` , the jar wouldn't be included.

**Comment by pmendelski** [comment]
👍  Good to know, thanks!
