### ISSUE TITLE
Unable to generate manifest with Spring Boot's dedicated "assemble" tasks

### ISSUE THREAD

**Issue by x80486** [coditory/gradle-manifest-plugin#33]
## Context

I have a `Spring Boot` application. I've tried to integrate this plugin and everything works fine until the moment any of the built-in "assemble" tasks from `Spring Boot` is used.

## Expected Behavior

For the plugin to be able to integrate correctly, generate the manifest along with the specific `Spring Boot` entries.

## Observed Behavior

```shell
[x80486@uplink:~/Workshop/Development/mockserver-sandbox]$ ./gradlew installBootDist 
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.6/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
> Task :generateEffectiveLombokConfig UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :manifest
> Task :classes UP-TO-DATE
> Task :bootJarMainClassName
> Task :bootJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootJar'.
> Entry META-INF/MANIFEST.MF is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I can certainly workaround this by setting `setDuplicatesStrategy(DuplicatesStrategy.EXCLUDE)` inside `BootJar`'s task, but that's the same as not having/using the plugin. In my case, I see that `Spring Boot` needs these entries (probably less or more depending on how the builds are finally configured):

```shell
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: org.acme.Application
Spring-Boot-Version: 2.7.8
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Spring-Boot-Classpath-Index: BOOT-INF/classpath.idx
Spring-Boot-Layers-Index: BOOT-INF/layers.idx
```

...and that's what gets saved in `META-INF/MANIFEST.MF`, rather than the merge from it and what the plugin outputs.

> It's not clear to me if this problem falls into the plugin or if it's something that needs to be done on the `Spring Boot` side, but I guess the plugin could identify the task(s) that will generate the manifest and append/write the configured entries after.

## Steps to Reproduce

1. Generate a `Spring Boot` project — https://start.spring.io/
2. Integrate the plugin in the `Gradle` build script
3. Execute `./gradlew installBootDist`

## Your Environment

* Plugin version: `0.2.6`
* Java (and/or Kotlin) version: `11.0.17 Eclipse Adoptium`
* Gradle version: `7.6`
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Link to your project (if it's a public repository): N/A

**Comment by anderso** [comment]
I guess there's a general issue with other plugins or tasks that add entries to the manifiest. I encountered this when trying to use this plugin with the official Java application plugin: https://docs.gradle.org/current/userguide/application_plugin.html#application_plugin

This plugin will generate a mainclass entry in the manifest using this extension:

```
application {
    mainClass.set("org.gradle.sample.Main")
}

```

But when using this plugin in the same build, the Main-Class entry will not be included in MANIFEST.MF. So it would be nice if the plugin could add entries to the manifest, instead of replacing it.

**Comment by anderso** [comment]
Actually, nevermind my comment, I assumed that the application plugin should generate the manifest entry but I don't think it does.
