### ISSUE TITLE
Property classpathPrefix should not be OS dependent

### ISSUE THREAD

**Issue by Vity01** [coditory/gradle-manifest-plugin#6]
During a review I missed one possible problem.
Function `Path.of(extension.classpathPrefix, it.name)` returns different result for Windows x Linux and the build system can be different from the OS launching the jar. 
Eg. for `classpathPrefix = "libs"` it will result in `"libs\some.jar"` on Windows, on Linux results in `"libs/some.jar" `
With `"libs\some.jar"` in the classpath it won't work on Linux OS.
Also nowadays the usage of `Path.of` breaks build tests on Windows. 

I suggest a simple fix - remove `Path.of` call. I think it's a correct solution to let user define the whole path , include the slash (eg. `libs/`), the plugin just concats the strings.

**Comment by pmendelski** [comment]
Hi,

User or system dependent separators might lead to other portability problems.
I've just released new version `0.1.12` in which classpath prefix is translated to unix path.
I believe JVM on windows should handle unix paths correctly.

Could you please check this solution?

**Comment by Vity01** [comment]
It's working. Although I think the simple solution would be good enough. 
Thank you.

**Comment by pmendelski** [comment]
Thanks for checking it up.

Could you explain how the simple solution could work?
When someone builds a jar on Windows and moves it to Linux then Linux JVM will throw error on `\` file separator.
