### ISSUE TITLE
Unable to pre-configure Manifest-plugin from another plugin 

### ISSUE THREAD

**Issue by Vity01** [coditory/gradle-manifest-plugin#7]
Hello @pmendelski ,
I develop a custom plugin which pre-define common values for multiple different plugins at once . One of them is the Manifest-plugin. 
Unfortunately I am unable to set values for ManifestExtension. The whole Manifest-plugin's configuration is initialized immediately during plugin initialization phase (`apply()` method) so the values overriding is not possible. 
I use this piece of code to define values in my plugin:
```
            if ((config.enableManifestInfo || config.enableJarClasspath)
                && !pluginManager.hasPlugin(ManifestPlugin.PLUGIN_ID)) {
                pluginManager.apply(ManifestPlugin.PLUGIN_ID) //activates plugin
            }
            if (config.enableJarClasspath) {
                //  manifest-plugin already set up all values :-(
                project.plugins.withType<ManifestPlugin> {  // cannot be done without plugin ManifestPlugin.apply()
                    configure<ManifestPluginExtension> {
                         classpathPrefix = "libs"
                    }
                }
            }
```
I made some experiments locally and with a minor change it started to work - in `ParameterizedManifestPlugin.apply` function I enclosed `setupPlugin` in this block:
```
        project.afterEvaluate {
            setupPlugin(project, extension)
        }
```
I am not sure if only function `fillAttributes` should be placed inside of that block (that would make a sense to me) or together with `setupGenerateManifestTask`, but this variant also worked for me:
```
    override fun apply(project: Project) {
        if (!project.plugins.hasPlugin(JavaPlugin::class.java)) {
            project.plugins.apply(JavaPlugin::class.java)
        }
        val extension = setupExtension(project)
        setupPlugin(project)
        project.afterEvaluate {
            fillAttributes(clock, hostNameResolver, project, extension)
        }

    }

    private fun setupExtension(project: Project): ManifestPluginExtension {
        return project.extensions.create(MANIFEST_EXTENSION, ManifestPluginExtension::class.java)
    }

    private fun setupPlugin(project: Project) {
        setupGenerateManifestTask(project)
    }


```

I am not an expert for Gradle plugin development, you might have a better idea how to solve the issue. 

EDIT1: I talked to one of my colleague and he suggests the second solution I mentioned.
EDIT2: Another colleague recommends to read extension configuration when the Task is launched or defined, but it has one disadvantage - it fails later than during a configuration phase (after jar is built... etc).
He would put the `fillAttrbutes` method somewhere inside this block: https://github.com/coditory/gradle-manifest-plugin/blob/cae2a04d0a4f5e95cad7bd3b037bff5e559b928e/src/main/kotlin/com/coditory/gradle/manifest/ParameterizedManifestPlugin.kt#L37

**Comment by pmendelski** [comment]
Hi again ;) 

Could you help me reproduce this problem in a sample project:
https://github.com/coditory/gradle-manifest-plugin-sample/blob/check-lazy-attributes/build.gradle.kts#L10

I added a plugin directly in `build.gradle.kts` that modifies manifest extension but all seems to work fine.

**Comment by Vity01** [comment]
Hello Pavel, thank you for the counterexample :-). After the last few hours of digging, we have found out possible problem in the another plugin, which is calling `project.tasks.findByName("jar")`. This plugin is applied before yours and it looks like `findByName` activates your callback for `fillAttributes` (in ManifestAttributes). We will try to avoid the findByName invocation.
If you have some idea how to avoid this situation then please let me know. 
I will put our solution/workaround here if I find any.

**Comment by Vity01** [comment]
The code which helped us to resolve the problem:
```groovy
        project.tasks.named("jar") {
            project.logger.info("XXXX - Task Jar named")
            def jarTask = it
           // do something with jarTask
        }
```

Thanks again for the test case.
