### ISSUE TITLE
JVM Target 1.8

### ISSUE THREAD

**Issue by Vity01** [coditory/gradle-manifest-plugin#9]
Hello,
is there any special reason to use `jvmTarget = 11` ? We would like to use it also for old docker images with a base jdk 8. 
Could you set `jvmTarget` to 1.8 to make it compatible with this JDK as well?

**Comment by pmendelski** [comment]
Hi, I added support to Java 1.8 in version `0.1.13`.

**Comment by Vity01** [comment]
Thank you, you are the best.
